### ISSUE TITLE
Ability to control reset password 

### ISSUE THREAD

**Issue by keshansandeepa** [Tecdiary/mps-guide#1]
Give a setting to add the availability or non availability to  password reset option

**Comment by MianSaleem** [comment]
Password reset option is already there. If that's not what you are saying then can you please provide more details so that I can understand the issue. Thanks

**Comment by keshansandeepa** [comment]
Give a option to admin to enable or disable password resetting

**Comment by MianSaleem** [comment]
How this can be helpful? 

How if admin himself forgot password?
