### ISSUE TITLE
Bug after add payment on sales, after transaction

### ISSUE THREAD

**Issue by agustinus-robert** [Tecdiary/mps-guide#10]
500 internal server error, when i want complete invoice sale

**Comment by MianSaleem** [comment]
Can you please test again. Thanks

**Comment by mksadmin** [comment]
I am also getting 500 internal server error, and when I add an omount (not full payment) doesn´t apply that amount.
Question, does MPOS has mutiple payments on complete invoice sale? for exampla 50 on cash, 30 Credit Card, 60 Other.

**Comment by MianSaleem** [comment]
Hello,

Might be something related to development or deploy. I will check.

Payments are not attached to sales/purchases in MPS but to customers/suppliers and you can add payment as you need as many times. 

Thank you

**Comment by saifwolf** [comment]
Dear Mian,
Good day, this is confusing, how can we add payment t sale so we can now how much left on that invoice t pay ?
on Stock Manager Adavnced it was very simple., we open the sales invoice with i.e. total amount of 100$ , we add payment of 30$ , now due is 70$ and paid is 30$, how can we track payment for invoices on MPS ?

Regards
