### ISSUE TITLE
Login Input Field Option 

### ISSUE THREAD

**Issue by keshansandeepa** [Tecdiary/mps-guide#2]
These days they don't normally create emails. Therefore Add option to customised login input eg(phone number).

**Comment by MianSaleem** [comment]
User would be able to login with username or email. I will add the phone option too. 

There will be option for sms and email notifications. 

Thank you

**Comment by MianSaleem** [comment]
I have checked, user can login using phone number as username. The validation on for email will be removed if phone isn't empty. Thank you
