### ISSUE TITLE
Loading animation gets locked

### ISSUE THREAD

**Issue by markelerrasti** [Tecdiary/mps-guide#5]
When you go to add a product to cart the loading animation gets locked. I am really interested on this theme but I would need to perfectionate the theme.

**Comment by MianSaleem** [comment]
This is still work in progress. We will check. Thank you for letting us know

**Comment by MianSaleem** [comment]
Hello,

I have updated the demo again. Can you please check now. If you still have same issue, please copy the page url or take screenshot for me.

Thank you
